### ISSUE TITLE
Hi there

### ISSUE THREAD

**Issue by simp-god** [sgade/swiftui-mapview#1]
I'm getting an issue with this. It's saying No such module DeveloperToolsSupport in LibraryViewContent. I'm not really sure what that means

**Comment by sgade** [comment]
Hi, you're absolutely right. The import was added to support Xcode 12's new `LibraryContentProvider` feature. I did not test it with the iOS 13 SDK, tough, and that is where it fails to compile.

Will quickly fix it and create a new release! Thanks for bringing this up.

**Comment by sgade** [comment]
See the 1.1.1 release.
