### ISSUE TITLE
Push destination on NavList, when selecting a MapViewAnnotation?

### ISSUE THREAD

**Issue by JMCPH** [sgade/swiftui-mapview#3]
Hi.

I'm trying to "push" a detail view onto a NavigationList, when a user have tapped MapViewAnnotation.

I have tried several ideas, but I'm unable to succeed. Do you guys have any hint or idea of how this problem could be approached?

`            // For the selected
            ForEach(self.selectedAnnotations.compactMap { $0 as? DogParkAnnotation }) { annotation in
                // Push on NavList.
            }`

**Comment by sgade** [comment]
Hi, the way this functionality is supported is via the `selectedAnnotations` binding. The value of that field includes any annotations the user has selected.

Based on the field value you need to filter the correct state for your app. Then you need to setup a `NavigationLink` that is activated when you want to present your detail view. See the initialisers with `isActive` parameters.
