### ISSUE TITLE
Modifying state during view update, this will cause undefined behavior.

### ISSUE THREAD

**Issue by chenlidongorg** [sgade/swiftui-mapview#4]
很感谢你写出这么好用的一个代码，出现一个提示：
Modifying state during view update, this will cause undefined behavior.

问题出现在这里
```swift
// MARK: MKMapViewDelegate
        public func mapView(_ mapView: MKMapView, didSelect view: MKAnnotationView) {
            guard let mapAnnotation = view.annotation as? MapViewAnnotation else {
                return
            }
            
            self.context.selectedAnnotations.append(mapAnnotation)
        }
```

建议修改，新增一个异步进程即可消除。
```swift
// MARK: MKMapViewDelegate
        public func mapView(_ mapView: MKMapView, didSelect view: MKAnnotationView) {
            guard let mapAnnotation = view.annotation as? MapViewAnnotation else {
                return
            }

            DispatchQueue.main.async {
                // 新增一个异步进程

                self.context.selectedAnnotations.append(mapAnnotation)
            }
        }
```

**Comment by sgade** [comment]
Hi, @chenlidongorg. Thanks for your suggestion. I was using DeepL for translating your comments but from what I understood this looks fine.

How did you notice the problem? Were there any strange problems in one of your apps?

I you could create a small pull request, that would be great!

**Comment by sgade** [comment]
I had some time and did the fix myself. Version `1.2.1` includes it.

I am still interested in how the issue surfaced on your end.
